stages:
  - build

image: docker:latest

#
# build
#
build:
  stage: build
  services:
    - docker:dind
  script:
    - wget https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x64_linux.tar.gz
    - wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    - wget https://github.com/git/git/archive/refs/tags/v2.35.1.tar.gz
    - docker build -t centos-git-java-maven:0.0.2 .
  only:
    - main
