docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t centos-git-java-maven:0.0.1 .
  after_script:
    - docker images
  only:
    - build
