stages:
  - build

#
# build
#
build:
  stage: build
  script:
    - apt-get install ca-certificates curl gnupg lsb-release
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    - sudo apt-get install docker-ce docker-ce-cli containerd.io
    - wget --content-disposition https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x64_linux.tar.gz
    - wget --content-disposition https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    - wget --content-disposition https://github.com/git/git/archive/refs/tags/v2.35.1.tar.gz
    - docker build -t centos-git-java-maven:0.0.1 .
  only:
    - build
